# backup
# docker exec -t your-db-container pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
# restore
# cat your_dump.sql | docker exec -i your-db-container psql -U postgres
# restore from backup
# docker cp .\aicos.backup postgres12:/aicos_backup
# docker exec -i postgres12 pg_restore -U postgres -d aicos_default /aicos.backup

version: '3.7'

services:
    postgres14:
        image: postgres:14
        container_name: "postgres14"
        ports:
            - "${POSTGRES_PORT}:5432"
        tty: true
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - postgres_network
        restart: always
        environment:
            - PGHOST=localhost
            - PGDATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    pgadmin:
        container_name: pgadmin_4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-luismanuelp1992@gmail.com}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - pgadmin_network
        depends_on:
            - postgres14
        restart: unless-stopped

volumes:
    db-data:
        driver: local
    pgadmin:
networks:
    postgres_network:     
        name: postgres_network
    pgadmin_network:     
        name: pgadmin_network
